### ISSUE TITLE
Add npm (compatible) package

### ISSUE THREAD

**Issue by tp** [skhilko/StickyHeaders#1]
Since many project use npm/bower packages for dependency management, it would be nice if this were on there.

Should just be a simple addition to the package.json.

I have this on my TODO list as well, so hopefully I can provide a PR shortly.

**Comment by skhilko** [comment]
Thanks for the request Timm! I'll work on that shortly.
Need to figure out the best way of integrating a CommonJS module into the project build.

**Comment by skhilko** [comment]
- Added support for AMD and CommonJS modules
- Published NPM and Bower packages
